"""AutoEventMail: created

Revision ID: 894279efce9c
Revises: 2e814b095af0
Create Date: 2023-12-24 13:53:52.940610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '894279efce9c'
down_revision: Union[str, None] = '2e814b095af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autoeventmail',
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('days_shift', sa.Integer(), nullable=True),
    sa.Column('hours_shift', sa.Integer(), nullable=True),
    sa.Column('minutes_shift', sa.Integer(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('autoeventmail')
    # ### end Alembic commands ###
