"""Created EventSpeaker and EventVisitor tables

Revision ID: 70815b4c7cb7
Revises: a1fcb30fc95f
Create Date: 2023-11-21 10:16:57.478657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "70815b4c7cb7"
down_revision: Union[str, None] = "a1fcb30fc95f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eventspeaker",
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("speaker_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.id"],
        ),
        sa.ForeignKeyConstraint(
            ["speaker_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "speaker_id", name="unique_event_speaker_unit"),
    )
    op.create_table(
        "eventvisitor",
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("visitor_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.id"],
        ),
        sa.ForeignKeyConstraint(
            ["visitor_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "visitor_id", name="unique_event_visitor_unit"),
    )
    op.add_column("event", sa.Column("creator_id", sa.Integer(), nullable=False))
    op.create_foreign_key("event_creator_id_fkey", "event", "user", ["creator_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("event_creator_id_fkey", "event", type_="foreignkey")
    op.drop_column("event", "creator_id")
    op.drop_table("eventvisitor")
    op.drop_table("eventspeaker")
    # ### end Alembic commands ###
