"""UserRole: added unique constraint

Revision ID: a1fcb30fc95f
Revises: 053267007432
Create Date: 2023-11-05 11:00:50.394629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a1fcb30fc95f"
down_revision: Union[str, None] = "053267007432"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("unique_user_role_unit", "userrole", ["user_id", "role_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_user_role_unit", "userrole", type_="unique")
    # ### end Alembic commands ###
