"""added new fields in User table

Revision ID: 93d5bff68ba0
Revises: 316625080310
Create Date: 2023-10-07 10:57:20.968246

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93d5bff68ba0"
down_revision: Union[str, None] = "316625080310"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("first_name", sa.String(length=100), nullable=True))
    op.add_column("user", sa.Column("last_name", sa.String(length=100), nullable=True))
    op.alter_column("user", "bdate", existing_type=sa.DATE(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "bdate", existing_type=sa.DATE(), nullable=False)
    op.drop_column("user", "last_name")
    op.drop_column("user", "first_name")
    # ### end Alembic commands ###
