"""create connection user-region

Revision ID: 316625080310
Revises: eb0db914c31c
Create Date: 2023-10-06 17:10:41.046927

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "316625080310"
down_revision: Union[str, None] = "eb0db914c31c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("region_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "user", "region", ["region_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_column("user", "region_id")
    # ### end Alembic commands ###
