"""Event: added roles col

Revision ID: 2e814b095af0
Revises: fd3f4b0000cf
Create Date: 2023-11-24 20:31:24.606881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2e814b095af0"
down_revision: Union[str, None] = "fd3f4b0000cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event", sa.Column("roles", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event", "roles")
    # ### end Alembic commands ###
