"""added archived column in role table

Revision ID: 156c06295ac2
Revises: b566c94da080
Create Date: 2023-11-04 18:39:47.001121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "156c06295ac2"
down_revision: Union[str, None] = "b566c94da080"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("role", sa.Column("archived", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("role", "archived")
    # ### end Alembic commands ###
