"""region_id was made null True in User

Revision ID: 678a40130aec
Revises: 09e517f0447a
Create Date: 2023-10-08 12:13:04.970986

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "678a40130aec"
down_revision: Union[str, None] = "09e517f0447a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "region_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "region_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
