"""deleted Admin, Creator_ Speaker

Revision ID: a507052501c5
Revises: 1ffe0260c9bd
Create Date: 2023-11-03 22:45:04.553244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a507052501c5'
down_revision: Union[str, None] = '1ffe0260c9bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    op.drop_table('speaker')
    op.drop_table('creator')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='creator_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='creator_pkey'),
    sa.UniqueConstraint('user_id', name='creator_user_id_key')
    )
    op.create_table('speaker',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='speaker_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='speaker_pkey'),
    sa.UniqueConstraint('user_id', name='speaker_user_id_key')
    )
    op.create_table('admin',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='admin_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='admin_pkey'),
    sa.UniqueConstraint('user_id', name='admin_user_id_key')
    )
    # ### end Alembic commands ###
