"""AutoEventMail: added send_datetime&send_now fields

Revision ID: 5fec69cdee54
Revises: d54bab6d49bb
Create Date: 2024-01-14 20:52:52.892416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fec69cdee54'
down_revision: Union[str, None] = 'd54bab6d49bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autoeventmail', sa.Column('send_datetime', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('autoeventmail', sa.Column('send_now', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('autoeventmail', 'send_now')
    op.drop_column('autoeventmail', 'send_datetime')
    # ### end Alembic commands ###
