"""GroupVK: max len token - 500

Revision ID: 14a8b102158a
Revises: c306001bec85
Create Date: 2024-03-10 23:04:46.686408

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14a8b102158a"
down_revision: Union[str, None] = "c306001bec85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "groupvk", "token", existing_type=sa.VARCHAR(length=100), type_=sa.String(length=500), existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "groupvk", "token", existing_type=sa.String(length=500), type_=sa.VARCHAR(length=100), existing_nullable=False
    )
    # ### end Alembic commands ###
