"""added session to user model

Revision ID: 1f0fdde06c04
Revises: 2e814b095af0
Create Date: 2024-02-03 00:29:15.042807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f0fdde06c04'
down_revision: Union[str, None] = '2e814b095af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('session', sa.String(length=36), nullable=True))
    op.add_column('user', sa.Column('session_expiration', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'user', ['session'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'session_expiration')
    op.drop_column('user', 'session')
    # ### end Alembic commands ###
