"""added archived column in region

Revision ID: 546149eff899
Revises: 14a8b102158a
Create Date: 2024-04-02 13:54:35.563771

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "546149eff899"
down_revision: Union[str, None] = "14a8b102158a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("region", sa.Column("archived", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("region", "archived")
    # ### end Alembic commands ###
