"""AutoEventMail: archived default is False

Revision ID: d54bab6d49bb
Revises: 894279efce9c
Create Date: 2024-01-06 21:03:32.911302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd54bab6d49bb'
down_revision: Union[str, None] = '894279efce9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('autoeventmail', 'archived',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('autoeventmail', 'archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
