"""added vk_group column in User

Revision ID: ae23866f2b2b
Revises: 5fec69cdee54
Create Date: 2024-03-10 22:02:44.850914

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae23866f2b2b"
down_revision: Union[str, None] = "5fec69cdee54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("vk_group", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "vk_group")
    # ### end Alembic commands ###
